### ISSUE TITLE
not a valid Win32 application

### ISSUE THREAD

**Issue by MercerMrc** [BrightSchema/Destiny-2-Discord-Rich-Presence#2]
Connects to Discord but stays blank due to an error:

```
Uncaught Error: \\?\C:\Users\Mercer\AppData\Local\Temp\0aa7a140-a8d1-4715-a2b8-4a43d839d755.tmp.node is not a valid Win32 application\\?\C:\Users\Mercer\AppData\Local\Temp\0aa7a140-a8d1-4715-a2b8-4a43d839d755.tmp.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (module.js:671:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:180:18)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at bindings (C:\Users\Mercer\AppData\Local\Programs\destiny-2-discord-rich-presence\resources\app.asar\node_modules\bindings\bindings.js:81:44)
    at Object.<anonymous> (C:\Users\Mercer\AppData\Local\Programs\destiny-2-discord-rich-presence\resources\app.asar\node_modules\better-sqlite3\lib\database.js:4:40)
```

```
Updated presence
presence.js:13 Uncaught (in promise) ReferenceError: rp is not defined
    at get (presence.js:13)
    at getRecentCharacter (presence.js:94)
    at pullNewData (populator.js:21)
    at setInterval (rp_updater.js:27)
```

Help with this would be much appreciated

**Comment by louis-bompart** [comment]
I managed to scramble a fix, I'll clean up the code a bit to have the minimal changeset and open a PR for that.

**Comment by BrightSchema** [comment]
Louis made a fix. I will soon try to merge what @louis-bompart did under the latest version
